name: Deploy Ionic Angular App

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn global add @ionic/cli

    - name: Install dependencies
      run: yarn install



    - name: Build Ionic Angular app for production
      run: ionic build --prod

    - name: Upload pages artifact
      id: upload-artifact
      uses: actions/upload-pages-artifact@v1
      with:
        publish-dir: 'www'
        artifact-name: 'my-site'
        publish-location: 'gh-pages'
  

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          publish_dir: ./www  # Change to your Angular build output directory
          publish_branch: gh-pages
